name: 02-Workflow-Event

on:
    pull_request:
    workflow_dispatch:

jobs:
  workflow-event-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow Event
        run: echo "This job was triggered by a ${{ github.event_name }} event."